### ISSUE TITLE
Photon causing problems in Unity Editor

### ISSUE THREAD

**Issue by EnricoTed** [oculus-samples/Unity-CrypticCabinet#9]
Hello, was wondering if you could help me figure this one out.

The game works perfectly if downloaded from the store. But when I try to open the project in the unity editor, it seems that the Photon SDK is not working correctly.

I keep getting all these errors as soon as we open the project. I tried setting up the meta app on the developer center, importing the PUN 2 SDK and setting up the app on the dashboard, but it still gives the same errors and I'm not sure why.

![immagine](https://github.com/oculus-samples/Unity-CrypticCabinet/assets/125978016/bbbf8cf7-2789-40b9-9025-336ceefb45fc)

If I open script mentioned in the unity errors, even more errors appear inside the script editor. They mention missing object types and methods and access to protected assets.

![immagine](https://github.com/oculus-samples/Unity-CrypticCabinet/assets/125978016/134eda16-1c29-42a3-b90f-f4e433e54b83)

I'm not quite sure how to solve this, because since the PUN SDK has not been updated in a long while I thought it unlikely to be a problem tied to an unmatching version. I realize it seems to be a problem more tied to Photon rather than to the project itself, but I haven't had any similar experiences using the very same package.

Thank you in advance.

**Comment by AlexThiv** [comment]
Hi @EnricoTed,

This looks like you downloaded the project directly instead of cloning using lfs.
See the [Getting the code](https://github.com/oculus-samples/Unity-CrypticCabinet?tab=readme-ov-file#getting-the-code) section.

Because of the use of LFS the photons dll when downloaded without lfs are only references to the actual lfs file, therefore not the actual DLL which would contain the missing scripts.

**Comment by EnricoTed** [comment]
Hi Alex,

That solved the issue, thank you very much.
